catalog/urls.py
from django.urls import path

import catalog.views
from catalog.autocomplete import course_autocomplete
from catalog.views import CategoryDetailView

urlpatterns = [
    path("course/<slug:slug>", catalog.views.show_course, name="course_show"),
    path("category/<int:pk>", CategoryDetailView.as_view(), name="category_show"),
    path("join/<slug:slug>", catalog.views.join_course, name="join_course"),
    path("leave/<slug:slug>", catalog.views.leave_course, name="leave_course"),
    path("subscribed_courses/", catalog.views.show_courses, name="show_courses"),
    path(
        "unfollow_all_courses/",
        catalog.views.unfollow_all_courses,
        name="unfollow_all_courses",
    ),
    path("course_tree.json", catalog.views.course_tree, name="course_tree"),
    path("search/autocomplete", course_autocomplete, name="course-autocomplete"),
    path(
        "finder/<slug:id>/<slug:category_slug>/",
        catalog.views.finder_turbo,
        name="finder_turbo",
    ),
    path(
        "finder/<slug:action>/<slug:course_slug>",
        catalog.views.finder_follow_course,
        name="set_course_follow",
    ),
]

www/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

import users.views
import www.views
from catalog.sitemap import CourseSitemap
from documents.sitemap import DocumentSitemap

sitemaps = {
    "course": CourseSitemap,
    "document": DocumentSitemap,
}

urlpatterns = [
    path("", www.views.index, name="index"),
    path("search/", include("search.urls")),
    path("catalog/", include(("catalog.urls", "catalog"), namespace="catalog")),
    path("documents/", include("documents.urls")),
    path("users/", include("users.urls")),
    path("moderation/", include("moderation.urls")),
    path("admin/", admin.site.urls),
    path("syslogin", LoginView.as_view(template_name="syslogin.html"), name="syslogin"),
    path("login", users.views.login_view, name="login"),
    path("auth-ulb", users.views.auth_ulb, name="auth-ulb"),
    path("logout", LogoutView.as_view(next_page="/"), name="logout"),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

handler400 = "www.error.error400"
handler403 = "www.error.error403"
handler404 = "www.error.error404"
handler500 = "www.error.error500"

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path("favicon.ico", www.views.favicon),
    ]

    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns.extend(
            [
                path("__debug__/", include(debug_toolbar.urls)),
            ]
        )

catalog/models.py
from datetime import timedelta

from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, db_index=True, unique=True)
    description = models.TextField(blank=True, default="")
    parents = models.ManyToManyField(
        "self",
        blank=True,
        symmetrical=False,
        related_name="children",
    )

    is_archive = models.BooleanField(default=False)

    class CategoryType(models.TextChoices):
        BACHELOR = "BA", _("Bachelier")
        MASTER = "MA", _("Master")
        MASTER_SPECIALIZATION = "MS", _("Master de spécialisation")
        CERTIFICATE = "CERT", _("Certificat")
        AGGREGATION = "AGG", _("Agrégation")
        UNIVERSITY = "UNI", _("Université")
        FACULTY = "FAC", _("Faculté")
        BLOC = "BLOC", _("Bloc")

    type = models.CharField(
        max_length=4,
        choices=CategoryType.choices,
        default=None,
        null=True,
    )

    class Meta:
        verbose_name_plural = "categories"
        ordering = ["id"]

    def __str__(self):
        return self.name

    def better_name(self):
        name = self.name
        name = (
            name.removeprefix("Faculté de ")
            .removeprefix("Faculté d'")
            .removeprefix("Faculté des ")
        )
        name = name.replace(
            "Agrégation de l'enseignement secondaire supérieur - ", ""
        ).replace(
            "Certificat d'aptitude pédagogique approprié à l'enseignement supérieur - ",
            "",
        )
        name = name.replace("Master en enseignement section ", "Enseignement ")

        name = name.removeprefix("Bachelier en ").removeprefix("Bachelier : ")
        name = (
            name.removeprefix("Master en ")
            .removeprefix("Master : ")
            .removeprefix("Master de spécialisation en ")
            .removeprefix("Master de ")
        )

        if "orientation" in name:
            name = name.replace("orientation générale", "orientation Général").replace(
                "orientation ", "("
            ) + ")".replace("Général à finalité", "")
        rr = {
            "Haute Ecole Libre de Bruxelles": "HELB",
            "Institut des Hautes Etudes des Communications Sociales": "IHECS",
            "Solvay": "Solvay",
        }
        for k, v in rr.items():
            if k in name:
                name = v

        name = name.replace("sciences de la santé publique à finalité", "")
        name = name.replace(", (", " (")

        if "sciences de l'ingénieur (" in name:
            name = name.replace("sciences de l'ingénieur (", "").replace(")", "")

        name = name.replace("(Général)", "")

        name = name.replace(" ,", ",").replace("( ", "(")

        name = name.replace(", option Bruxelles", "")
        name = name.replace("(Site de Charleroi)", "(Charleroi)")
        name = name.replace("(Site de Mons)", "(Mons)")
        name = name.replace("(Général à finalité ", "(")

        name = name.replace("option SOIR", "(soir)")
        name = name.replace("option JOUR", "")

        name = name.replace("), (", ", ")
        name = name.removesuffix(", ")

        return name


class PeriodType(models.TextChoices):
    FIRST = "Q1", _("1er quadri")
    SECOND = "Q2", _("2ème quadri")
    BOTH = "Y", _("Toute l'année")
    UNKNOWN = "?", _("Inconnu")


class Course(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(unique=True, db_index=True)
    categories = models.ManyToManyField(Category, through="CourseCategory")  # type: ignore
    description = models.TextField(default="")
    period = models.CharField(
        max_length=4,
        choices=PeriodType,
        default=PeriodType.UNKNOWN,
    )

    followed_by = models.ManyToManyField("users.User", related_name="courses_set")
    is_archive = models.BooleanField(default=False)

    class Meta:
        ordering = ["slug"]

    def gehol_url(self):
        slug = self.slug.replace("-", "").upper()
        return f"https://gehol.ulb.ac.be/gehol/Vue/HoraireCours.php?cours={slug}"

    def get_absolute_url(self):
        return reverse("catalog:course_show", args=(self.slug,))

    def __str__(self):
        return self.slug

    def fullname(self):
        return f"{self.name} ({self.slug.lower()})"

    @property
    def followers_count(self) -> int:
        return self.followed_by.count()


class CourseCategory(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    mandatory = models.BooleanField(default=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["course", "category"], name="unique_course_category"
            ),
        ]


class CourseUserView(models.Model):
    user = models.ForeignKey("users.User", on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    views = models.IntegerField(default=1)
    last_view = models.DateTimeField(auto_now=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user", "course"], name="unique_user_course_view"
            ),
        ]

    @classmethod
    def visit(cls, user, course: Course):
        obj, created = cls.objects.get_or_create(user=user, course=course)
        if not created and (timezone.now() - obj.last_view) > timedelta(minutes=5):
            # Do not use F("views") + 1 here as we DO want a race condition to happen.
            # Indeed, if the user loads 2 pages at the same instant, we want to count only
            # one of them (as we count a new page view every 5 min only)
            obj.views = obj.views + 1
            obj.save()

catalog/forms.py
from django import forms


class SearchForm(forms.Form):
    name = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Chercher un cours (exemple : info-h-100 ou Microéconomie)"
            }
        ),
    )

catalog/views.py
from dataclasses import dataclass
from functools import wraps

from django.contrib.auth.decorators import login_required
from django.db.models import Case, Count, Q, Value, When
from django.http import Http404, HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.decorators.http import require_POST

from catalog.models import Category, Course, CourseUserView
from catalog.slug import normalize_slug
from documents.models import Vote


def slug_redirect(view):
    @wraps(view)
    def wrapper(request: HttpRequest, slug: str, *args, **kwargs):
        try:
            normalized = normalize_slug(slug)
        except ValueError:
            raise Http404("This is not a valid course slug.") from None
        if normalized != slug:
            return redirect(request.path.replace(slug, normalized))
        return view(request, slug, *args, **kwargs)

    return wrapper


@slug_redirect
def show_course(request, slug: str):
    course = get_object_or_404(Course, slug=slug)

    if not request.user.is_authenticated:
        display = Q(hidden=False)
    elif request.user.is_staff:
        display = Q()
    else:
        display = Q(hidden=True, user=request.user) | Q(hidden=False)

    documents = (
        course.document_set.exclude(state="ERROR")
        .filter(display)
        .select_related("course", "user")
        .prefetch_related("tags", "vote_set")
        .annotate(upvotes=Count("vote", filter=Q(vote__vote_type=Vote.VoteType.UPVOTE)))
        .annotate(
            downvotes=Count("vote", filter=Q(vote__vote_type=Vote.VoteType.DOWNVOTE))
        )
        .order_by("-created")
    )

    context = {
        "course": course,
        "tags": {tag for doc in documents for tag in doc.tags.all()},
        "documents": documents,
        "following": course.followed_by.filter(id=request.user.id).exists(),
    }

    if request.user.is_authenticated:
        template = "catalog/course.html"
        CourseUserView.visit(request.user, course)
    else:
        template = "catalog/noauth/course.html"

    return render(request, template, context)


@login_required
@slug_redirect
def set_follow_course(request, slug: str, action: str) -> HttpResponse:
    """Makes a user either follow or unfollow a course"""
    course = get_object_or_404(Course, slug=slug)
    if action == "follow":
        course.followed_by.add(request.user)
    else:
        course.followed_by.remove(request.user)
    course.save()
    nextpage = request.GET.get("next", reverse("catalog:course_show", args=[slug]))
    return HttpResponseRedirect(nextpage)


@login_required
@slug_redirect
@require_POST
def join_course(request: HttpRequest, slug: str):
    return set_follow_course(request, slug, "follow")


@login_required
@slug_redirect
@require_POST
def leave_course(request: HttpRequest, slug: str):
    return set_follow_course(request, slug, "leave")


@login_required
def my_courses(request):
    # "suggestions": suggest(request.user),
    return render(
        request,
        "catalog/my_courses.html",
    )


@login_required
def unfollow_all_courses(request):
    request.user.courses_set.clear()
    return redirect("home")


@dataclass
class Column:
    category: Category
    children: list[Category]
    depth: int
    category_prefix: str


def finder(request, slugs: str = ""):
    slug_list = slugs.split("/")
    categories = [get_object_or_404(Category, slug=x) for x in slug_list]

    for i in range(len(categories) - 1, 0, -1):
        parents = categories[i].parents.all()

        if categories[i - 1] not in parents:
            raise Http404(f"Invalid category path, {i}")

    columns = []
    max_depth = len(categories)
    for i, category in enumerate(categories):
        depth = max_depth - i
        path_list = ["."] + [".."] * (depth - 1)
        columns.append(
            Column(
                category,
                list(
                    category.children.order_by(
                        Case(
                            When(type=Category.CategoryType.BACHELOR, then=Value(0)),
                            When(type=Category.CategoryType.MASTER, then=Value(1)),
                            When(
                                type=Category.CategoryType.MASTER_SPECIALIZATION,
                                then=Value(2),
                            ),
                            When(
                                type=Category.CategoryType.AGGREGATION,
                                then=Value(3),
                            ),
                            default=Value(4),
                        ),
                        "name",
                    ).all()
                ),
                depth,
                "/".join(path_list),
            )
        )

    return render(
        request,
        "catalog/finder.html",
        {
            "columns": columns,
            "extra_columns": range(4 - len(columns)),
            "is_archive": categories[0].is_archive,
        },
    )


def finder_root(request):
    ulb = get_object_or_404(Category, slug="ULB")
    return redirect(reverse("catalog:finder", args=[ulb.slug]))

catalog/templates/catalog/finder.html
{% extends "base.html" %}
{% load static %}

{% block title %}Liste des cours{% endblock %}

{% block content %}
    {% comment %}
    <nav aria-label="breadcrumb" class="d-none d-md-block">
        <ol class="breadcrumb">
            {% for column in columns %}
                <li class="breadcrumb-item"><a href="{{ column.category_prefix }}/">{{ column.category.name }}</a></li>
            {% endfor %}
        </ol>
    </nav>
    {% endcomment %}
    {% if is_archive %}
        <div class="alert alert-info" role="alert">
            <h4 class="alert-heading">
                Archives
            </h4>
            Le programme de cours de l'ULB a parfois beaucoup changé au cours des années.
            Tu te trouves ici dans les archives des années précédentes.
        </div>
    {% else %}
        <div class="alert alert-success" role="alert">
            Le programme de cours de l'ULB a parfois beaucoup changé au cours des années.
            Si tu ne trouves plus des documents des années précédentes,
            <a href="/catalog/f/archives/">regarde dans les archives</a> !
        </div>
    {% endif %}
    <div class="d-flex gap-2">
        {% for column in columns %}
            <div
                class="border p-2 rounded flex-grow-1 flex-basis-0 w-100 {% if not forloop.last %}d-none d-md-block{% endif %}">
                <h5>
                    {% if forloop.last and not forloop.first %}
                        <div class="d-inline-flex d-md-none hover-scale">
                            <a href="../">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
                                    <path
                                        d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                                </svg>
                            </a>
                        </div>
                    {% endif %}
                    {{ column.category.name }}
                </h5>
                <ul class="p-0" style="list-style: none;">
                    {% regroup column.children by get_type_display as children_groups %}
                    {% for type in children_groups %}
                        {% if type.grouper != "OTHE" %}
                            <li>
                                <div class="d-flex align-items-center gap-1 fs-5 border-bottom">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                         fill="currentColor" class="bi bi-mortarboard" viewBox="0 0 16 16">
                                        <path
                                            d="M8.211 2.047a.5.5 0 0 0-.422 0l-7.5 3.5a.5.5 0 0 0 .025.917l7.5 3a.5.5 0 0 0 .372 0L14 7.14V13a1 1 0 0 0-1 1v2h3v-2a1 1 0 0 0-1-1V6.739l.686-.275a.5.5 0 0 0 .025-.917l-7.5-3.5ZM8 8.46 1.758 5.965 8 3.052l6.242 2.913L8 8.46Z"/>
                                        <path
                                            d="M4.176 9.032a.5.5 0 0 0-.656.327l-.5 1.7a.5.5 0 0 0 .294.605l4.5 1.8a.5.5 0 0 0 .372 0l4.5-1.8a.5.5 0 0 0 .294-.605l-.5-1.7a.5.5 0 0 0-.656-.327L8 10.466 4.176 9.032Zm-.068 1.873.22-.748 3.496 1.311a.5.5 0 0 0 .352 0l3.496-1.311.22.748L8 12.46l-3.892-1.556Z"/>
                                    </svg>
                                    <div>{{ type.grouper }}{{ type.list|pluralize }}</div>
                                </div>
                            </li>
                        {% endif %}
                        {% for subcat in type.list %}
                            <li>
                                <a href="{{ column.category_prefix }}/{{ subcat.slug }}/"
                                   class="text-body text-decoration-none">
                                    <div class="d-flex align-items-center my-1 ">
                                        <div class="flex-shrink-0 px-2 py-1">

                                        </div>
                                        <div class="flex-grow-1 hover-underline">
                                            {{ subcat.better_name|capfirst }}
                                        </div>
                                    </div>
                                </a>
                            </li>
                        {% endfor %}
                    {% endfor %}
                    {% for course in column.category.course_set.all %}
                        <li>
                            <a href="{% url "catalog:course_show" course.slug %}"
                               class="text-body text-decoration-none">
                                <div class="d-flex align-items-center my-1 border-bottom">
                                    <div class="flex-shrink-0 px-2 py-1">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                             fill="currentColor"
                                             class="bi bi-folder" viewBox="0 0 16 16">
                                            <path
                                                d="M.54 3.87.5 3a2 2 0 0 1 2-2h3.672a2 2 0 0 1 1.414.586l.828.828A2 2 0 0 0 9.828 3h3.982a2 2 0 0 1 1.992 2.181l-.637 7A2 2 0 0 1 13.174 14H2.826a2 2 0 0 1-1.991-1.819l-.637-7a1.99 1.99 0 0 1 .342-1.31zM2.19 4a1 1 0 0 0-.996 1.09l.637 7a1 1 0 0 0 .995.91h10.348a1 1 0 0 0 .995-.91l.637-7A1 1 0 0 0 13.81 4H2.19zm4.69-1.707A1 1 0 0 0 6.172 2H2.5a1 1 0 0 0-1 .981l.006.139C1.72 3.042 1.95 3 2.19 3h5.396l-.707-.707z"/>
                                        </svg>
                                    </div>
                                    <div class="flex-grow-1">
                                        <span class="hover-underline">{{ course.name }}</span>
                                        <small class="text-muted text-nowrap">{{ course.slug|upper }}</small>
                                    </div>
                                </div>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        {% endfor %}
        {% for column in extra_columns %}
            <div class="border flex-grow-1 flex-basis-0 w-100 d-none d-md-block">

            </div>
        {% endfor %}
    </div>

{% endblock content %}

catalog/templates/catalog/like-dislike.html
{% load like_tags %}

<turbo-frame id="like-dislike-{{ document.pk }}" class="card-like">
    {% user_liked request.user document as liked %}
    <a class="like" href="{% url "document_vote" document.pk %}?vote_type=up">
        <i class="fas fa-thumbs-up" style="grid-row-start:1;{% if liked == "up" %}color: #43AC6A;{% endif %}"></i>
        <span>{{ document.votes.upvotes }}</span>
    </a>
    <a class="dislike" href="{% url "document_vote" document.pk %}?vote_type=down">
        <i class="fas fa-thumbs-down" style="grid-row-start:2;{% if liked == "down" %}color: #9e1d1d;{% endif %}"></i>
        <span>{{ document.votes.downvotes }}</span>
    </a>
</turbo-frame>

catalog/templates/catalog/my_courses.html
{% extends "base.html" %}
{% load static %}

{% block title %}Liste des cours{% endblock %}

{% block content %}
    {% if user.following_courses|length > 0 %}
        <a href="{% url 'catalog:unfollow_all_courses' %}" class="button red hide-on-mobile" style="position: absolute;right: 2em;top: 3em;">
            Me désabonner de tous les cours
        </a>
    {% endif %}
{% endblock content %}